[project]
name = "layaflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maroofiums", email = "maroof96965@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[all]>=0.141.1",
    "laya>=0.3.5",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "uvicorn>=0.53.0",
]

[project.scripts]
layaflow = "layaflow:main"

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
